### ISSUE TITLE
Missing prosilica_gige_sdk command line tools

### ISSUE THREAD

**Issue by mitchellwills** [ros-drivers/prosilica_driver#4]
In hydro all of the command line tools (SampleViewer, ListCameras, etc.) that used to be distributed in the prosilica_gige_sdk package appear to be missing. The package also seems to have been removed from this repository during the cakinization process.

**Comment by wjwwood** [comment]
I think the `prosilica_gige_sdk` is released separately now, @ahendrix did the releasing so I'll let him comment on that.

**Comment by trainman419** [comment]
The prosilica gige sdk is now released separately: https://github.com/ros-drivers/prosilica_gige_sdk . This was done because it is a separate library, and because it allows me to version it separately.

The manual clearly states:

> Distribution
> The following files may be redistributed for use with Prosilica/AVT cameras only:
> PvAPI.dll
> PvNET.dll
> PvJNI.dll
> psligvfilter.inf
> psligvfilter_m.inf
> psligvfilter.sys
> Allied Vision Technologies GigE Filter Installer.exe
> Allied Vision Technologies Viewer Installer.exe
> libPvAPI.so
> libPvAPI.a
> libImagelib.a
> ￼￼￼No other files from the SDK may be redistributed without written permission from Allied Vision Technologies.

Since I was not able to find record of having received written permission to redistribute the example programs, I am no longer distributing them.
